require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "tests"
  t.test_files = FileList['tests/test_game.rb',
                          'tests/test_monster.rb']
  t.verbose = true
end

task(default: :test)
